export const ActionTypes = {
  SET_USER: "SET_USERS",
  SELECTED_USER: "SELECTED_USER",
  REMOVE_SELECTED_USER: "REMOVE_SELECTED_USER",
  SET_SORT_PARAMS: "SET_SORT_PARAMS",
  SORT_ASCENDING: "SORT_ASCENDING",
  SORT_DESCENDING: "SORT_DESCENDING",
};
